### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by trje3733** [radical-experiments/adaptive-bms-experiments#1]
Hi @vivek-bala, I started using the new EE scripts and have ran into a few errors (below). I tried a few things to try and correct the errors but am not sure they are exactly correct. For the first, changed line #83 to "if it == 1:". For the second, changed line 216 to "appman.assign_workflow(pipelines_set)".  If these changes were made I ran into the third. Please let me know if there is any way I can help.

1st error:
Traceback (most recent call last):
  File "runme.py", line 177, in <module>
    pipelines_set.add(get_pipeline(i, TOTAL_ITERS))
  File "runme.py", line 87, in get_pipeline
    t2.copy_input_data += [ '$Pipeline_%s_Stage_%s_Task_%s/CB7G3_run.mdp'%(p.uid, s4.uid, t4.uid), 
UnboundLocalError: local variable 's4' referenced before assignment

2nd error:
Traceback (most recent call last):
  File "runme.py", line 216, in <module>
    appman.assign_workflow(pipes_set)
NameError: name 'pipes_set' is not defined

3rd:
2017-11-29 15:30:44,260: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2017-11-29 15:30:44,260: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/TravisJensen/anaconda2/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 241, in run
    self._resource_manager._submit_resource_request()
  File "/home/TravisJensen/anaconda2/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 341, in _submit_resource_request
    self._pilot.wait([rp.ACTIVE, rp.FAILED])
AttributeError: 'module' object has no attribute 'ACTIVE'

wait for 1 pilot(s)

**Comment by vivek-bala** [comment]
Hey Travis, the first two fixes seem correct. Thanks.

I edited the README with additional instructions to resolve the 3rd error. Specifically:

You need to set a few environment variables: ```export RP_ENABLE_OLD_DEFINES=True``` and Change line 722 of ```$VE/lib/python2.7/site-packages/radical/pilot/configs/resource_xsede.json``` ($VE points to your virtualenv) from ```module load python``` to ```module load python/2.7.7-anaconda```.

**Comment by trje3733** [comment]
Thanks, that seems to have fixed the issues.
